### PR TITLE
Updates and Bug Fixes

### LINKED ISSUE #28: Bug on view blog
When clicking on the blog from the profile page to view I get the following error

Screen Shot 2021-08-27 at 1 40 18 PM

### PR DESCRIPTION
**Pull request by kevin-carlson**
Updated feedDAC dep to v0.2.4. 
- Now allows for post filtering by domain (ie only feedDAC posts created on skynetblog.hns)
- Each post now includes full ref, fixing the issue when routing from My Blogs page to individual blog view.

Added error handling to blog and profile pages. This handles cases where the URL params do not have a post or user associated with the given values.

Fixes #28

### CODE REVIEW

File: src/data/feedLibrary.js [hunk 1]
```diff
@@ -41,6 +40,7 @@ export async function loadBlogPost(ref, feedDAC) {
  * @return {object} post object data in SkyStandards format
  */
 export async function loadBlogProfile(userID, feedDAC) {
-  const postsLoader = await feedDAC.loadPostsForUser(userID);
+  const blogSkapps = ["skynetblog.hns"]; //skapps paths to load posts from
```
Comment (MSevey) [inline src/data/feedLibrary.js:43]: Follow Up: `skynetblog.hns` is not referenced in a lot of placed. This should be pulled into a const somewhere that all the locations can reference. 

`src/data/consts.js` for example.

**Comment by MSevey** [comment]
I tested the app, should I see my old blogs in this version or no?

Additionally when I post the blog, it is successful. I click on the blog and it takes me to my profile but it doesn't show any blogs again.

**Review by MSevey — APPROVED** [review]
